version: "3.8"

services:
  web:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/src/app
      - ./libs:/usr/src/libs
    command: air ./cmd/main.go -b 0.0.0.0
    environment:
      - APP_PORT=${APP_PORT}
